Fix errors due to using CFLAGS -Wall -Werror
vmod_curl.c: In function 'recv_hdrs':
vmod_curl.c:176:16: error: unused variable 'e' [-Werror=unused-variable]
vmod_curl.c: In function 'cm_perform':
vmod_curl.c:222:18: error: unused variable 'h2' [-Werror=unused-variable]
vmod_curl.c:222:14: error: unused variable 'h' [-Werror=unused-variable]
vmod_curl.c:221:14: error: unused variable 'v' [-Werror=unused-variable]
vmod_curl.c:221:11: error: unused variable 'u' [-Werror=unused-variable]
vmod_curl.c:220:8: error: unused variable 'p' [-Werror=unused-variable]
vmod_curl.c: In function 'vmod_escape':
vmod_curl.c:482:11: error: unused variable 'cr' [-Werror=unused-variable]
vmod_curl.c: In function 'vmod_unescape':
vmod_curl.c:502:11: error: unused variable 'cr' [-Werror=unused-variable]